version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g typescript
      - npm install

  build:
    commands:
      - npm run build

cache:
  paths:
    - 'node_modules/**/*'

artifacts:
  files:
    - src/**/*
    - build/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
    - tsconfig.json
  discard-paths: no
