version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: lts
    commands:
      - npm install typescript@latest -g
      - npm install
  build:
    commands:
      - npx tsc

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'build/**/*'
  discard-paths: no
