version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install typescript -g
      - npm install

  pre_build:
    commands:
      - tsc

artifacts:
  files:
    - '**/*'
  discard-paths: yes
