version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g typescript
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      # - npm run test
      - npm prune --omit=dev
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
  discard-paths: no
