version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install typescript -g

  build:
    commands:
      - tsc

artifacts:
  files:
    - package.json
    - package-lock.json
    - 'tsconfig.json'

  discard-paths: no
